config/routes.rb
Loanager::Application.routes.draw do
  resources :transactions
  resources :people
    
  get "home/index"
  
  match 'admin', :to => 'access#dashboard'  
  match 'transaction/summary', :to => 'transactions#summary', :as => :transaction_summary
  match 'transaction/change-status/:id' => 'transactions#change_status', :as => :transaction_change_status

  resources :users do
    member do
      get :delete
    end
  end
  
    

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base
  
  # define relationships
  has_many :persons
  has_many :transactions
  has_one :person, :conditions => {:is_user => 1}
  
  #pagination size
  paginates_per 15
  
  # attribute accessors property
  attr_accessor :password  
  # normal property
  attr_protected :hashed_password, :salt
  
  
  # add validation
  validates_presence_of :username, :email
  validates_uniqueness_of :username
  validates_presence_of :password, :on => "create"
  # define filters 
  # create hashed password before saving the User object into database
  before_save :create_hashed_password
  # clear the password so that it doesn't always update 
  after_save :clear_password
  
  # custom model search method  
  scope :searh_all, where(["id > ?", 0])
  scope :searh_by_id, lambda{|id| where(["id = ?", "#{id}"])}
  
  
  ########## utility functions ####################
  def full_name
    "#{first_name} #{last_name}"
  end
  
  def self.make_salt(username = "")
    Digest::SHA1.hexdigest "#{username}#{Time.now}"
  end
  
  def self.hash_with_salt(password = "", salt = "")    
    Digest::SHA1.hexdigest "#{salt}#{password}"
  end
  
  def self.authenticate(username="", password="")
    user = User.find_by_username(username)
    if user && user.match_password(password)
      return user
    else
      return false
    end
  end
  
  def match_password(password="")
    return hashed_password == User.hash_with_salt(password, salt)
  end
  
  ################## private methods ########################
  private 
  def create_hashed_password
    #when password have a value
    unless password.blank?
      self.salt = User.make_salt username if self.salt.blank?      
      self.hashed_password = User.hash_with_salt(password, salt)
    end
  end
  
  def clear_password
    self.password = nil
  end 
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :confirm_logged_in
    
  def index
    list
    render "list"
  end
  
  def list
    @users = User.order(:created_at => "desc").page params[:page]
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new()
  end
  
  def create
    # instantiate the object
    @user = User.new(params[:user])
    #save the object
    if @user.save
      person = Person.new(:name => @user.first_name + " " + @user.last_name, :user_id => @user.id, :is_user => 1)
      if person.save
        flash[:notice] = "New profile created"
      end 
      #redirect
      flash[:notice] = "New user created"
      redirect_to @user
    else
      #view the form
      render "new"
    end
  end
  
  def edit
    #load the object
    @user = User.find(params[:id])    
  end
  
  def update
    #load the object
    @user = User.find(params[:id])
    #update the object
    if @user.update_attributes(params[:user])
      flash[:notice] = "User updated"
      redirect_to :action => "show", :id => @user.id
    else
      render "edit"
    end    
  end
  
  def delete
    @user = User.find(params[:id])
  end
  
  def destroy
    User.find(params[:id]).destroy
    redirect_to :action => "index"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= error_message_for_form @user %>

<%= form_for(@user) do |f| %>
	<table>
		<tr>
			<td><%= f.label :first_name %></td>
			<td><%= f.text_field(:first_name) %></td>
		</tr>
		<tr>
			<td><%= f.label :last_name %></td>
			<td><%= f.text_field(:last_name) %></td>
		</tr>
		<tr>
			<td><%= f.label :username %></td>
			<td><%= f.text_field(:username) %></td>
		</tr>
		<tr>
			<td><%= f.label :password %></td>
			<td><%= f.password_field(:password) %></td>
		</tr>
		<tr>
			<td><%= f.label :email %></td>
			<td><%= f.text_field(:email) %></td>
		</tr>
		<tr>
			<td><%= f.label :active %></td>
			<td><%= f.check_box(:active) %></td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td><%= submit_tag(submit_text, :class => "btn btn-primary") %></td>
		</tr>
	</table>	
<% end %>

app/views/users/delete.html.erb
<h3>Are you sure you want to delete this user: <%= @user.username %></h3>

<%= form_for (@user) do |f| %>
	<%= hidden_field_tag '_method', "delete"%>
	<%= submit_tag "Confirm" %>
	<%= link_to "Cancel", users_path %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>
<%= render :partial => "form", :locals => {:submit_text => "Update User"} %>

app/views/users/list.html.erb
<% @page_title = "User list" %>

<h1>User Management</h1>

<%= link_to "+ New User", new_user_path, :class => "btn btn-success pull-right add-link" %>


<table cellpadding="5" cellspacing="0" border="0" class="table table-bordered table-condensed table-striped">
	<thead>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Username</th>
		<th>Email</th>
		<th>Action</th>
	</thead>
	<tbody>
		<% @users.each do |user|  %>
		<tr>
			<td><%= user.first_name %></td>
			<td><%= user.last_name %></td>
			<td><%= user.username %></td>
			<td><%= user.email %></td>
			<td>
				<%= link_to("View", user, {:class => "btn btn-info"}) %>
				<%= link_to("Edit", edit_user_path(user), {:class => "btn btn-primary"}) %>
				<%= link_to("Delete", delete_user_path(user), {:class => "btn btn-danger"}) %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

<%= paginate @users %>

app/views/users/new.html.erb
<h1>Create new user</h1>
<%= render :partial => "form", :locals => {:submit_text => "Add User"} %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<dl>
	<dt>First Name</dt>
	<dd><%= @user.first_name %></dd>
	
	<dt>Last Name</dt>
	<dd><%= @user.last_name %></dd>
	
	<dt>Username</dt>
	<dd><%= @user.username %></dd>
		
	<dt>Email</dt>
	<dd><%= @user.email %></dd>
	
	<dt>Active</dt>
	<dd><%= @user.active ? "yes" : "No" %></dd>
	
	<dt>Created</dt>
	<dd><%= @user.created_at %></dd>
	
	<dt>Updated</dt>
	<dd><%= @user.updated_at %></dd>
</dl>

<%= link_to "Back", users_path, :class => "btn" %>