config/routes.rb
Loanager::Application.routes.draw do
  resources :transactions
  resources :people
    
  get "home/index"
  
  match 'admin', :to => 'access#dashboard'  
  match 'transaction/summary', :to => 'transactions#summary', :as => :transaction_summary
  match 'transaction/change-status/:id' => 'transactions#change_status', :as => :transaction_change_status

  resources :users do
    member do
      get :delete
    end
  end
  
    

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :confirm_logged_in
  
  # GET /transactions
  def index
    query = params[:show_paid].present? ? {:user_id => current_user.id, :is_paid => 1} : {:user_id => current_user.id, :is_paid => 0}  
    @transactions = Transaction.where(query).page params[:page]
  end

  # GET /transactions/1
  def show
    @transaction = Transaction.find(params[:id])
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions
  def create
    @transaction = Transaction.new(params[:transaction])
    @transaction.title = @transaction.from_name + " >> " + @transaction.to_name;
    if @transaction.save
      redirect_to(@transaction, :notice => 'Transaction was successfully created.')
    else
      render :action => "new"
    end
  end

  # PUT /transactions/1
  def update
    @transaction = Transaction.find(params[:id])
    if @transaction.update_attributes(params[:transaction])
      redirect_to(@transaction, :notice => 'Transaction was successfully updated.')
    else
      render :action => "edit"
    end
  end

  # DELETE /transactions/1
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy
    redirect_to(transactions_url)
  end
  
  def summary
    #raise current_user.person.inspect
    @user_gave = Transaction.where(:from => current_user.person, :is_paid => 0).page params[:page]
    @user_took = Transaction.where(:to => current_user.person, :is_paid => 0).page params[:page]
  end
  
  def change_status
    transaction = Transaction.find(params[:id])
    if transaction.is_paid?
      transaction.is_paid = 0
      transaction.save
      redirect_to transactions_url(:show_paid => "yes"), :notice => 'Transaction is due.'
    else
      transaction.is_paid = 1
      transaction.save
      redirect_to transactions_url, :notice => 'Transaction is paid.'
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= error_message_for_form @transaction %>

<%= form_for @transaction, :html => {:class => "form-horizontal"} do |f| %>
  <div class="control-group">
  	<%= f.label :description, :class =>"control-label" %>
  	<div class="controls"><%= f.text_area :description, :rows => 5, :class =>"input-xlarge" %></div>
  </div>
  <div class="control-group">
    <%= f.label :from, :class =>"control-label" %>
    <% 
    	person_array = Person.where(:user_id => current_user.id).map{ |person|
    		[person.name, person.id]
    	} 
    %>
    <div class="controls"><%= f.select :from, person_array%></div>
  </div>
  <div class="control-group">
    <%= f.label :to, :class =>"control-label" %>
    <div class="controls"><%= f.select :to, person_array%></div>
  </div>
  <div class="control-group">
    <%= f.label :amount, :class =>"control-label" %>
    <div class="controls"><%= f.text_field :amount %></div>
  </div>  
  <div class="control-group">
    <%= f.label :is_paid, :class =>"control-label" %>
    <div class="controls"><%= f.check_box :is_paid %></div>
  </div>  
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="form-actions">
    <%= f.submit :class => "btn-primary" %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction, :class => "btn btn-info" %>
<%= link_to 'Back', transactions_path, :class => "btn" %>

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<p><%= link_to '+ New Transaction', new_transaction_path, {:class => "btn btn-success pull-right add-link"} %></p>

<table class="table table-bordered table-condensed table-striped">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>From</th>
    <th>To</th>
    <th>Amount</th>
    <th>Action</th>
  </tr>

<% @transactions.each do |transaction| %>
  <tr>
    <td><%= transaction.title %></td>
    <td><%= transaction.description %></td>
    <td><%= transaction.from_name %></td>
    <td><%= transaction.to_name %></td>
    <td><%= transaction.amount %></td>
    <td>
    	<%= link_to 'Show', transaction, {:class => "btn btn-info"} %> 
    	<%= link_to 'Edit', edit_transaction_path(transaction), {:class => "btn btn-primary"} %>
    	<%= link_to 'Delete', transaction, :class => "btn btn-danger", :confirm => 'Are you sure?', :method => :delete %>
    	<% if transaction.is_paid? %>
    		<%= link_to 'Mark as due', transaction_change_status_path(transaction.id), :class => "btn"%>
    	<% else %>
    		<%= link_to 'Mark as paid', transaction_change_status_path(transaction.id), :class => "btn"%>
    	<% end %>
    </td>
  </tr>
<% end %>
</table>

<%= paginate @transactions %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path, :class => "btn" %>

app/views/transactions/show.html.erb
<h1><%= @transaction.title %></h1>

<p>
  <b>Title:</b>
  <%= @transaction.title %>
</p>

<p>
  <b>Description:</b>
  <%= @transaction.description %>
</p>

<p>
  <b>From:</b>
  <%= @transaction.from_name %>
</p>

<p>
  <b>To:</b>
  <%= @transaction.to_name %>
</p>

<p>
  <b>Amount:</b>
  <%= @transaction.amount %>
</p>

<p>
  <b>Paid:</b>
  <%= @transaction.is_paid? ? "Yes" : "No" %>
</p>


<%= link_to 'Edit', edit_transaction_path(@transaction), :class => "btn btn-info" %>
<%= link_to 'Back', transactions_path, :class => "btn" %>

app/views/transactions/summary.html.erb
<%
#raise @user_gave.inspect
gtotal = ttotal = 0
%>
<h3>People took from me</h3>
<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th>To</th>
			<th>Purpose</th>
			<th>Amount</th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	<tbody>
	<% @user_gave.each do |g| %>	
		<tr>
			<td><%= g.to_name %></td>
			<td><%= g.description %></td>
			<td><%= g.amount %></td>
			<td>&nbsp;</td>
		</tr>
		<% gtotal += g.amount %>
	<% end %>
		<tr>
			<td colspan="3">Total given</td>
			<td><%= gtotal %></td>
		</tr>
	</tbody>
</table>
 
 <%= paginate @user_gave %>
 
<h3>I took from people</h3>
<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th>From</th>
			<th>Purpose</th>
			<th>Amount</th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	<tbody>
	<% @user_took.each do |t| %>
		<tr>
			<td><%= t.from_name %></td>
			<td><%= t.description %></td>
			<td><%= t.amount %></td>
			<td>&nbsp;</td>
		</tr>
		<% ttotal += t.amount %>
	<% end %>
		<tr>
			<td colspan="3">Total taken</td>
			<td><%= ttotal %></td>
		</tr>
	</tbody>
</table>
 <%= paginate @user_took %>