config/routes.rb
Loanager::Application.routes.draw do
  resources :transactions
  resources :people
    
  get "home/index"
  
  match 'admin', :to => 'access#dashboard'  
  match 'transaction/summary', :to => 'transactions#summary', :as => :transaction_summary
  match 'transaction/change-status/:id' => 'transactions#change_status', :as => :transaction_change_status

  resources :users do
    member do
      get :delete
    end
  end
  
    

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/_navbar.html.erb
<div class="row">
<div id="navbar" class="navbar navbar-static">
  <div class="navbar-inner">
    <div class="container" style="width: auto;">
      <a class="brand" href="/">Loanager</a>
      <ul class="nav">
      	<% if logged_in? %>
	      	<% if current_user.id == 1 %>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle">Users <b class="caret"></b></a>
	          <ul class="dropdown-menu">
	            <li><%= link_to ("List Users", users_path) %></li>
	            <li class="divider"></li>
	            <li><%= link_to ("Add New User", new_user_path) %></li>
	          </ul>
	        </li>
	        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle">People <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to ("List People", people_path) %></li>
            <li><%= link_to ("Add New People", new_person_path) %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle">Transactions <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to ("List all transactions", transactions_path) %></li>
            <li><%= link_to "List all paid transactions", transactions_path(:show_paid => "yes") %></li>
            <li><%= link_to ("Add New transaction", new_transaction_path) %></li>
            <li class="divider"></li>
            <li><%= link_to ("Transaction summary", :controller => "transactions", :action => "summary") %></li>
          </ul>
        </li>
        <% end %>
      </ul>
      <ul class="nav pull-right">        
          <% if logged_in? %>
						<li class="name"><%= "Hello #{session[:username]}" %></li> 
						<li><%= link_to ("Dashboard", :controller => "access", :action =>"dashboard") %></li> 
						<li><%= link_to ("Logout", :controller => "access", :action =>"logout") %></li>
					<% else %>
						<li class="name"><%= "Hello Guest" %> </li>
						<li><%= link_to ("Login", :controller => "access", :action =>"login") %></li>
					<% end %>
        </li>
      </ul>
    </div>
  </div>
</div> <!-- /navbar-example -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Loanager | <%= @page_title %></title>
		<%= stylesheet_link_tag "bootstrap", :media => "all" %>
		<%= stylesheet_link_tag "styles", :media => "all" %>
		<%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Berkshire+Swash" %>
		
		<%= javascript_include_tag "prototype", "rails" %>		
		<%= javascript_include_tag "jquery-1.7.1.min" %>
		<%= javascript_include_tag "application" %>
		<%= javascript_include_tag "bootstrap-dropdown" %>
		<%= csrf_meta_tag %>
	</head>
	<body>
		<div class="container">
			<%= render :partial => "layouts/navbar" %>
			<div class="row content">				
					<% if flash[:notice] %>
						<div class="alert alert-info">
							<%= flash[:notice]%>
						</div>
					<% end %>
				<%= yield %>
			</div>
		</div>
	</body>
</html>